export const navList = [
  {
    title: "Početna",
    link: "/",
  },

  {
    title: "Proizvodi",
    link: "/proizvodi",
  },
  {
    title: "Kontakt",
    link: "/kontakt",
  },
];

export interface ProductList {
  id: number;
  title: string;
  text: string;
  price: number;
  images: string[];
}

export const productList = [
  {
    id: 1,
    title: "Listele biber crepa 30x15cm",
    text: "Sečene od autentičnog starog biber crepa, ove pločice dimenzija 30x15 cm idealne su za podne i zidne obloge. Izrađene od prirodnih materijala, odlikuju se visokim stepenom otpornosti na spoljne uticaje i mogu podneti teret veći od 12 tona. Savršen izbor za rustične i moderne prostore koji zahtevaju dugotrajnost i estetsku vrednost.",
    price: 7,
    ground: " - podna i zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " - Podnosi opterecenje 12 tona",

    images: [
      "/Listele biber crepa 30x15.jpg",
      "/Listele biber crepa 30x15 2.jpg",
      "/Listele biber crepa 30x15 3.jpg",
      "/Listele biber crepa 30x15 4.jpg",
      "/Listele biber crepa 30x15 5.jpg",
      "/Listele biber crepa 30x15 6.jpg",
    ],
  },
  {
    id: 2,
    title: "Listele od biber crepa 15x5 cm",
    text: "Sečene od autentičnog starog biber crepa, ove pločice dimenzija 15x5 cm idealne su za zidne obloge. Izrađene od prirodnih materijala, odlikuju se visokim stepenom otpornosti na spoljne uticaje. Savršen izbor za rustične i moderne prostore koji zahtevaju dugotrajnost i estetsku vrednost.",
    price: 14,
    ground: " - zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " - samo za staze bez vecih opterecenja",
    images: [
      "/Listele od biber crepa 15x5 cm 2.jpg",
      "/Listele od biber crepa 15x5 cm.jpg",
    ],
  },
  {
    id: 3,
    title: "Dekorativne ciglice od biber crepa 8x30 cm",
    text: "Sečene od autentičnog starog biber crepa, ove pločice dimenzija 8x30 cm idealne su za podne i zidne obloge. Izrađene od prirodnih materijala, odlikuju se visokim stepenom otpornosti na spoljne uticaje i mogu podneti velika opterecenja. Savršen izbor za rustične i moderne prostore koji zahtevaju dugotrajnost i estetsku vrednost.",
    price: 9,
    ground: " - podna i zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " - Podnosi velika opterecenja",
    images: [
      "/Dekorativne ciglice od biber crepa 8x30 cm 2.jpg",
      "/Dekorativne ciglice od biber crepa 8x30 cm.jpg",
      "/Dekorativne ciglice od biber crepa 8x30 cm 3.jpg",
      "/Dekorativne ciglice od biber crepa 8x30 cm 4.jpg",
      "/Dekorativne ciglice od biber crepa 8x30 cm 5.jpg",
    ],
  },
  {
    id: 4,
    title: "Dekorativne ciglice 15x30 cm – crveno-žuta kombinacija",
    text: "Ove dekorativne ciglice dimenzija 15x30 cm, u kombinaciji crvenih i žutih tonova, idealne su za podne i zidne obloge. Sečene od prirodnih materijala, odlikuju se visokom otpornošću na spoljne uticaje i mogu podneti velika opterećenja. Pored izdržljivosti, pružaju i odličnu toplotnu izolaciju, čineći svaki prostor estetski privlačnim i energetski efikasnim.",
    price: 9,
    ground: " - podna i zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " - Podnosi velika opterecenja",
    images: [
      "/Listele i dekorativne ciglice 15 x 30 cm.jpg",
      "/Listele i dekorativne ciglice 15 x 30 cm 2.jpg",
    ],
  },
  {
    id: 5,
    title: "Dekorativne ciglice 26x5,5 cm",
    text: "Ove dekorativne ciglice dimenzija 26x5,5 cm simulacija fasadne cigle, u kombinaciji crvenih i žutih tonova, idealne su za podne i zidne obloge. Sečene od prirodnih materijala, odlikuju se visokom otpornošću na spoljne uticaje i mogu podneti velika opterećenja. Pored izdržljivosti, pružaju i odličnu toplotnu izolaciju, čineći svaki prostor estetski privlačnim i energetski efikasnim.",
    price: 11,
    ground: " - podna i zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " - Podnosi velika opterecenja",
    images: ["/Dekorativne ciglice 26x5,5 cm.jpg"],
  },
  {
    id: 6,
    title: "Dekorativna italijanska ciglica",
    text: "Savršen izbor za fasade i dekorativne detalje, ove italijanske ciglice kombinuju estetiku i izdržljivost. Otporne na spoljašnje uticaje, garantuju dugotrajnost i autentičan izgled. Izrada se vrši isključivo po narudžbini, prilagođena vašim potrebama i viziji prostora.",
    price: 60,
    ground: " - zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " - nije za velika opterecenja",
    images: [
      "/Dekorativna italijanska ciglica.jpg",
      "/Dekorativna italijanska ciglica2.jpg",
      "/Dekorativna italijanska ciglica3.jpg",
      "/Dekorativna italijanska ciglica4.jpg",
      "/Dekorativna italijanska ciglica5.jpg",
      "/Dekorativna iatlijanska ciglica6.jpg",
      "/Dekorativna italijanska ciglica7.jpg",
      "/Dekorativna italijanska ciglica8.jpg",
    ],
  },
  {
    id: 7,
    title: "Listele od biber crepa 30x15 zute",
    text: "Sečene od autentičnog starog biber crepa, ove pločice dimenzija 30x15 cm idealne su za podne i zidne obloge. Izrađene od prirodnih materijala, odlikuju se visokim stepenom otpornosti na spoljne uticaje i mogu podneti teret veći od 12 tona. Savršen izbor za rustične i moderne prostore koji zahtevaju dugotrajnost i estetsku vrednost.",
    price: 10,
    ground: " - podna i zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " - Podnosi opterecenje 12 tona",
    images: [
      "/Listele od biber crepa 30x15 zute.jpg",
      "/Listele od biber crepa 30x15 zute2.jpg",
    ],
  },
  {
    id: 8,
    title: "Prirodni lomljeni kamen",
    text: "Izrađen od 100% prirodnog materijala, ovaj kamen je idealan za zidne i podne obloge. Odlikuje se visokom otpornošću na spoljne uticaje i velika opterećenja, pružajući dugotrajnost i autentičnu estetiku. Savršen izbor za eksterijere i enterijere koji zahtevaju prirodnu eleganciju i izdržljivost.",
    price: 7,
    ground: " - podna i zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " - Podnosi velika opterecenja",
    images: [
      "/Prirodni lomljeni kamen.jpg",
      "/Prirodni lomljeni kamen 2.jpg",
      "/Prirodni lomljeni kamen 3.jpg",
      "/Prirodni lomljeni kamen 4.jpg",
      "/Prirodni lomljeni kamen 5.jpg",
    ],
  },
  {
    id: 9,
    title: "Suvi zid, od prirodnog kamena",
    text: "Izrađen od prirodnog kamena, ovaj suvi zid namenjen je isključivo za zidne površine. Odlikuje se visokim stepenom otpornosti na sve spoljne uticaje, pružajući dugotrajnost, stabilnost i autentičan rustični izgled. Idealan za eksterijere i enterijere koji zahtevaju prirodnu eleganciju i čvrstoću.",
    price: 12,
    ground: " - zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " - nije za velika opterecenja",
    images: [
      "/Suvi zid, od prirodnog kamena.jpg",
      "/Suvi zid, od prirodnog kamena 2.jpg",
    ],
  },
  {
    id: 10,
    title: "Seceni prirodni kamen stanglica 3cm",
    text: "Ove tigraste štanglice širine 3 do 8 cm izrađene su od prirodnog kamena i namenjene isključivo za zidne obloge. Odlikuju se čvrstoćom i otpornošću, što ih čini idealnim za unutrašnje i spoljašnje dekoracije. Prirodna tekstura i jedinstveni tonovi unose toplinu i eleganciju u svaki prostor.",
    price: 22,
    ground: " - zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " - nije za velika opterecenja",
    images: ["/Seceni prirodni kamen stanglica.jpg"],
  },
  {
    id: 11,
    title: "Seceni prirodni kamen stanglica 5cm",
    text: "Ove tigraste štanglice širine 3 do 8 cm izrađene su od prirodnog kamena i namenjene isključivo za zidne obloge. Odlikuju se čvrstoćom i otpornošću, što ih čini idealnim za unutrašnje i spoljašnje dekoracije. Prirodna tekstura i jedinstveni tonovi unose toplinu i eleganciju u svaki prostor.",
    price: 21,
    ground: " - podna i zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " - nije za velika opterecenja",
    images: ["/Seceni prirodni kamen stanglica.jpg"],
  },
  {
    id: 12,
    title: "Seceni prirodni kamen stanglica 8cm",
    text: "Ove tigraste štanglice širine 3 do 8 cm izrađene su od prirodnog kamena i namenjene isključivo za zidne obloge. Odlikuju se čvrstoćom i otpornošću, što ih čini idealnim za unutrašnje i spoljašnje dekoracije. Prirodna tekstura i jedinstveni tonovi unose toplinu i eleganciju u svaki prostor.",
    price: 20,
    ground: " - zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " - nije za velika opterecenja",
    images: ["/Seceni prirodni kamen stanglica.jpg"],
  },
  {
    id: 13,
    title: "Seceni prirodni kamen, stanglice plave 3cm",
    text: "Ove plave štanglice širine 3 do 8 cm izrađene su od prirodnog kamena i namenjene isključivo za zidne obloge. Odlikuju se čvrstoćom i otpornošću, što ih čini idealnim za unutrašnje i spoljašnje dekoracije. Prirodna tekstura i jedinstveni tonovi unose toplinu i eleganciju u svaki prostor.",
    price: 22,
    ground: " - zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " -nije za velika opterecenja",
    images: ["/Seceni prirodni kamen, stanglice plave.jpg"],
  },
  {
    id: 14,
    title: "Seceni prirodni kamen, stanglice plave 5cm",
    text: "Ove plave štanglice širine 3 do 8 cm izrađene su od prirodnog kamena i namenjene isključivo za zidne obloge. Odlikuju se čvrstoćom i otpornošću, što ih čini idealnim za unutrašnje i spoljašnje dekoracije. Prirodna tekstura i jedinstveni tonovi unose toplinu i eleganciju u svaki prostor.",
    price: 20,
    ground: " - zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " - nije za velika opterecenja",
    images: ["/Seceni prirodni kamen, stanglice plave.jpg"],
  },
  {
    id: 15,
    title: "Seceni prirodni kamen, stanglice plave 8cm",
    text: "Ove plave štanglice širine 3 do 8 cm izrađene su od prirodnog kamena i namenjene isključivo za zidne obloge. Odlikuju se čvrstoćom i otpornošću, što ih čini idealnim za unutrašnje i spoljašnje dekoracije. Prirodna tekstura i jedinstveni tonovi unose toplinu i eleganciju u svaki prostor.",
    price: 19,
    ground: " - zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " - nije za velika opterecenja",
    images: ["/Seceni prirodni kamen, stanglice plave.jpg"],
  },
  {
    id: 16,
    title: "Seceni prirodni kamen, stanglice bronza 3cm",
    text: "Ove bronzane štanglice širine 3 do 8 cm izrađene su od prirodnog kamena i namenjene isključivo za zidne obloge. Odlikuju se čvrstoćom i otpornošću, što ih čini idealnim za unutrašnje i spoljašnje dekoracije. Prirodna tekstura i jedinstveni tonovi unose toplinu i eleganciju u svaki prostor.",
    price: 21.5,
    ground: " - zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " - nije za velika opterecenja",
    images: ["/Seceni prirodni kamen, stanglice bronza.jpg"],
  },
  {
    id: 17,
    title: "Seceni prirodni kamen, stanglice bronza 5cm",
    text: "Ove bronzane štanglice širine 3 do 8 cm izrađene su od prirodnog kamena i namenjene isključivo za zidne obloge. Odlikuju se čvrstoćom i otpornošću, što ih čini idealnim za unutrašnje i spoljašnje dekoracije. Prirodna tekstura i jedinstveni tonovi unose toplinu i eleganciju u svaki prostor.",
    price: 20.5,
    ground: " - zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " - nije za velika opterecenja",
    images: ["/Seceni prirodni kamen, stanglice bronza.jpg"],
  },
  {
    id: 18,
    title: "Seceni prirodni kamen, stanglice bronza 8cm",
    text: "Ove bronzane štanglice širine 3 do 8 cm izrađene su od prirodnog kamena i namenjene isključivo za zidne obloge. Odlikuju se čvrstoćom i otpornošću, što ih čini idealnim za unutrašnje i spoljašnje dekoracije. Prirodna tekstura i jedinstveni tonovi unose toplinu i eleganciju u svaki prostor.",
    price: 19,
    ground: " - zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " - nije za velika opterecenja",
    images: ["/Seceni prirodni kamen, stanglice bronza.jpg"],
  },
];
