export const navList = [
  {
    title: "Početna",
    link: "/",
  },

  {
    title: "Proizvodi",
    link: "/proizvodi",
  },
  {
    title: "Kontakt",
    link: "/kontakt",
  },
];

export interface Category {
  id: number;
  name: string;
  description: string;
  productIds: number[];
  image: string;
}

export const categoryList: Category[] = [
  {
    id: 3,
    name: "Dekorativni monolitni elementi",
    description: "Moderna rešenja sa integrisanom bojom i visokom otpornošću",
    productIds: [25, 26, 27, 28, 29, 30],
    image: "/vestacki/siga23 (9).jpg",
  },
  {
    id: 1,
    name: "Dekorativne ciglice od biber crepa",
    description: "Autentični materijali sečeni od starog biber crepa i opeke",
    productIds: [1, 2, 3, 4, 5, 7, 19, 20, 21, 22, 23, 24],
    image: "/svabska cigla.jpg",
  },
  {
    id: 2,
    name: "Prirodni kamen",
    description: "100% prirodni lomljeni kamen za zidne i podne obloge",
    productIds: [8],
    image: "/Prirodni lomljeni kamen.jpg",
  },
];

export interface ProductList {
  id: number;
  title: string;
  text: string;
  price: number;
  images: string[];
}

export const productList = [
  {
    id: 25,
    title: "Dekorativna monolitna siga",
    text: "Dekorativna monolitna siga je 100 postotno verna izgledu prirodne sige, posto je monolitna izradjena je iz jednog komada sa integrisanom bojom, bez slojeva i dodatnih farbanja. Predvidjena je za dekoraciju enterijera i eksterijera, otporna je na sve atmosferske uticaje , fizicka ostecenja nastala usled manjih udaraca grebanja paranja i slicnog. U slucaju ostecenja komad ne menja boju,ni strukturu. Nije preporucljivo bilo kakvo farbanje, a posto ima dodatke zastite nema potrebe za dodatnim lakiranjem i sticenjem , boja se moze naruciti po zelji kupca. tezina 1 m2 je 42 kg",
    price: 23,
    ground: "zidna obloga",
    eco: " - Veštački materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: "otporno na habanje",
    images: [
      "/vestacki/siga23 (5).jpg",
      "/vestacki/siga23 (1).jpg",
      "/vestacki/siga23 (3).jpg",
      "/vestacki/siga23 (4).jpg",
      "/vestacki/siga23 (6).jpg",
      "/vestacki/siga23 (7).jpg",
      "/vestacki/siga23 (8).jpg",
      "/vestacki/siga23 (9).jpg",
      "/vestacki/siga23 (10).jpg",
      "/vestacki/siga23 (11).jpg",
      "/vestacki/siga23 (12).jpg",
      "/vestacki/siga23 (13).jpg",
      "/vestacki/siga23 (14).jpg",
      "/vestacki/siga23 (15).jpg",
      "/vestacki/siga23 (16).jpg",
      "/vestacki/siga23 (17).jpg",
    ],
  },
  {
    id: 26,
    title: "Dekorativna monolitna siga",
    text: "Dekorativna monolitna siga je 100 postotno verna izgledu prirodne sige, posto je monolitna izradjena je iz jednog komada sa integrisanom bojom, bez slojeva i dodatnih farbanja. Predvidjena je za dekoraciju enterijera i eksterijera, otporna je na sve atmosferske uticaje , fizicka ostecenja nastala usled manjih udaraca grebanja paranja i slicnog. U slucaju ostecenja komad ne menja boju,ni strukturu. Nije preporucljivo bilo kakvo farbanje, a posto ima dodatke zastite nema potrebe za dodatnim lakiranjem i sticenjem , boja se moze naruciti po zelji kupca. tezina 1 m2 je 42 kg",
    price: 25,
    ground: "zidna obloga",
    eco: " - Veštački materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: "otporno na habanje",
    images: [
      "/vestacki/siga25 (5).jpg",
      "/vestacki/siga25 (6).jpg",
      "/vestacki/siga25 (7).jpg",
      "/vestacki/siga25 (8).jpg",
      "/vestacki/ siga25 (9).jpg",
      "/vestacki/siga25 (10).jpg",
      "/vestacki/siga25 (11).jpg",
      "/vestacki/siga25 (12).jpg",
      "/vestacki/siga25 (13).jpg",
      "/vestacki/siga25 (14).jpg",
      "/vestacki/siga25 (15).jpg",
      "/vestacki/siga25 (16).jpg",
      "/vestacki/siga25 (17).jpg",
      "/vestacki/siga25 (18).jpg",
      "/vestacki/siga25 (19).jpg",
      "/vestacki/siga25 (20).jpg",
      "/vestacki/siga25 (21).jpg",
      "/vestacki/siga25 (22).jpg",
      "/vestacki/siga25 (23).jpg",
      "/vestacki/siga25 (24).jpg",
      "/vestacki/siga25 (25).jpg",
      "/vestacki/siga25 (26).jpg",
      "/vestacki/siga25 (27).jpg",
      "/vestacki/siga25 (28).jpg",
      "/vestacki/siga25 (29).jpg",
      "/vestacki/siga25 (30).jpg",
      "/vestacki/siga25 (31).jpg",
      "/vestacki/siga25 (32).jpg",
      "/vestacki/siga25 (1).jpg",
      "/vestacki/siga25 (2).jpg",
      "/vestacki/siga25 (3).jpg",
      "/vestacki/siga25 (4).jpg",
    ],
  },
  {
    id: 27,
    title: "Dekorativne monolitne ciglice",
    text: "Dekorativna monolitna ciglica je 100 postotno verna izgledu prirodne ciglice, posto je monolitna izradjena je iz jednog komada sa integrisanom bojom, bez slojeva i dodatnih farbanja. Predvidjena je za dekoraciju enterijera i eksterijera, otporna je na sve atmosferske uticaje , fizicka ostecenja nastala usled manjih udaraca grebanja paranja i slicnog. U slucaju ostecenja komad ne menja boju,ni strukturu. Nije preporucljivo bilo kakvo farbanje, a posto ima dodatke zastite nema potrebe za dodatnim lakiranjem i sticenjem , boja se moze naruciti po zelji kupca. tezina 1 m2 je 30 kg",
    price: 20,
    ground: "zidna obloga",
    eco: " - Veštački materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: "otporno na habanje",
    images: [
      "/vestacki/ciglica20 (23).jpg",
      "/vestacki/ciglica20 (1).jpg",
      "/vestacki/ciglica20 (2).jpg",
      "/vestacki/ciglica20 (3).jpg",
      "/vestacki/ciglica20 (4).jpg",
      "/vestacki/ciglica20 (5).jpg",
      "/vestacki/ciglica20 (6).jpg",
      "/vestacki/ciglica20 (7).jpg",
      "/vestacki/ciglica20 (8).jpg",
      "/vestacki/ciglica20 (9).jpg",
      "/vestacki/ciglica20 (10).jpg",
      "/vestacki/ciglica20 (11).jpg",
      "/vestacki/ciglica20 (12).jpg",
      "/vestacki/ciglica20 (13).jpg",
      "/vestacki/ciglica20 (14).jpg",
      "/vestacki/ciglica20 (15).jpg",
      "/vestacki/ciglica20 (16).jpg",
      "/vestacki/ciglica20 (17).jpg",
      "/vestacki/ciglica20 (18).jpg",
      "/vestacki/ciglica20 (19).jpg",
      "/vestacki/ciglica20 (20).jpg",
      "/vestacki/ciglica20 (21).jpg",
      "/vestacki/ciglica20 (22).jpg",
      "/vestacki/ciglica20 (30).jpg",
      "/vestacki/ciglica20 (24).jpg",
      "/vestacki/ciglica20 (25).jpg",
      "/vestacki/ciglica20 (26).jpg",
      "/vestacki/ciglica20 (27).jpg",
      "/vestacki/ciglica20 (28).jpg",
      "/vestacki/ciglica20 (29).jpg",
    ],
  },
  {
    id: 28,
    title: "Dekorativne monolitne ciglice svetle boje",
    text: "Dekorativna monolitna ciglica je 100 postotno verna izgledu prirodne ciglice, posto je monolitna izradjena je iz jednog komada sa integrisanom bojom, bez slojeva i dodatnih farbanja. Predvidjena je za dekoraciju enterijera i eksterijera, otporna je na sve atmosferske uticaje , fizicka ostecenja nastala usled manjih udaraca grebanja paranja i slicnog. U slucaju ostecenja komad ne menja boju,ni strukturu. Nije preporucljivo bilo kakvo farbanje, a posto ima dodatke zastite nema potrebe za dodatnim lakiranjem i sticenjem , boja se moze naruciti po zelji kupca. tezina 1 m2 je 30 kg",
    price: 22,
    ground: "zidna obloga",
    eco: " - Veštački materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: "otporno na habanje",
    images: [
      "/vestacki/ciglica22 (1).jpg",
      "/vestacki/ciglica22 (2).jpg",
      "/vestacki/ciglica22 (3).jpg",
      "/vestacki/ciglica22 (4).jpg",
      "/vestacki/ciglica22 (5).jpg",
      "/vestacki/ciglica22 (6).jpg",
      "/vestacki/ciglica22 (7).jpg",
      "/vestacki/ciglica22 (8).jpg",
      "/vestacki/ciglica22 (9).jpg",
      "/vestacki/ciglica22 (10).jpg",
      "/vestacki/ciglica22 (11).jpg",
      "/vestacki/ciglica22 (12).jpg",
      "/vestacki/ciglica22 (13).jpg",
      "/vestacki/ciglica22 (14).jpg",
      "/vestacki/ciglica22 (15).jpg",
      "/vestacki/ciglica22 (16).jpg",
      "/vestacki/ciglica22 (17).jpg",
      "/vestacki/ciglica22 (18).jpg",
      "/vestacki/ciglica22 (19).jpg",
      "/vestacki/ciglica22 (20).jpg",
      "/vestacki/ciglica22 (21).jpg",
      "/vestacki/ciglica22 (22).jpg",
      "/vestacki/ciglica22 (23).jpg",
      "/vestacki/ciglica22 (24).jpg",
    ],
  },
  {
    id: 29,
    title: "Dekorativna monolitna bunja tamna",
    text: "Dekorativna monolitna bunja je 100 postotno verna izgledu prirodne bunje, posto je monolitna izradjena je iz jednog komada sa integrisanom bojom, bez slojeva i dodatnih farbanja. Predvidjena je za dekoraciju enterijera i eksterijera, otporna je na sve atmosferske uticaje , fizicka ostecenja nastala usled manjih udaraca grebanja paranja i slicnog. U slucaju ostecenja komad ne menja boju,ni strukturu. Nije preporucljivo bilo kakvo farbanje, a posto ima dodatke zastite nema potrebe za dodatnim lakiranjem i sticenjem , boja se moze naruciti po zelji kupca. tezina 1 m2 je 63 kg",
    price: 25,
    ground: "zidna obloga",
    eco: " - Veštački materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: "otporno na habanje",
    images: [
      "/vestacki/bunjatamnija (14).jpg",
      "/vestacki/bunjatamnija (1).jpg",
      "/vestacki/bunjatamnija (2).jpg",
      "/vestacki/bunjatamnija (3).jpg",
      "/vestacki/bunjatamnija (4).jpg",
      "/vestacki/bunjatamnija (5).jpg",
      "/vestacki/bunjatamnija (6).jpg",
      "/vestacki/bunjatamnija (7).jpg",
      "/vestacki/bunjatamnija (8).jpg",
      "/vestacki/bunjatamnija (9).jpg",
      "/vestacki/bunjatamnija (10).jpg",
      "/vestacki/bunjatamnija (11).jpg",
      "/vestacki/bunjatamnija (12).jpg",
      "/vestacki/bunjatamnija (13).jpg",
    ],
  },
  {
    id: 30,
    title: "Dekorativna monolitna bunja svetla",
    text: "Dekorativna monolitna bunja je 100 postotno verna izgledu prirodne bunje, posto je monolitna izradjena je iz jednog komada sa integrisanom bojom, bez slojeva i dodatnih farbanja. Predvidjena je za dekoraciju enterijera i eksterijera, otporna je na sve atmosferske uticaje , fizicka ostecenja nastala usled manjih udaraca grebanja paranja i slicnog. U slucaju ostecenja komad ne menja boju,ni strukturu. Nije preporucljivo bilo kakvo farbanje, a posto ima dodatke zastite nema potrebe za dodatnim lakiranjem i sticenjem , boja se moze naruciti po zelji kupca. tezina 1 m2 je 63 kg",
    price: 28,
    ground: "zidna obloga",
    eco: " - Veštački materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: "otporno na habanje",
    images: [
      "/vestacki/bunjasvetla (1).jpg",
      "/vestacki/bunjasvetla (16).jpg",
      "/vestacki/bunjasvetla (2).jpg",
      "/vestacki/bunjasvetla (3).jpg",
      "/vestacki/bunjasvetla (4).jpg",
      "/vestacki/bunjasvetla (5).jpg",
      "/vestacki/bunjasvetla (6).jpg",
      "/vestacki/bunjasvetla (7).jpg",
      "/vestacki/bunjasvetla (8).jpg",
      "/vestacki/bunjasvetla (9).jpg",
      "/vestacki/bunjasvetla (10).jpg",
      "/vestacki/bunjasvetla (11).jpg",
      "/vestacki/bunjasvetla (12).jpg",
      "/vestacki/bunjasvetla (13).jpg",
      "/vestacki/bunjasvetla (14).jpg",
      "/vestacki/bunjasvetla (15).jpg",
    ],
  },
  {
    id: 1,
    title: "Listele biber crepa 30x15cm",
    text: "Sečene od autentičnog starog biber crepa, ove pločice dimenzija 30x15 cm idealne su za podne i zidne obloge. Izrađene od prirodnih materijala, odlikuju se visokim stepenom otpornosti na spoljne uticaje i mogu podneti teret veći od 12 tona. Savršen izbor za rustične i moderne prostore koji zahtevaju dugotrajnost i estetsku vrednost.",
    price: 9,
    ground: " - podna i zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " - Podnosi opterecenje 12 tona",

    images: [
      "/Listele biber crepa 30x15 (4).jpg",
      "/Listele biber crepa 30x15 (1).jpg",
      "/Listele biber crepa 30x15 (2).jpg",
      "/Listele biber crepa 30x15 (3).jpg",
      "/Listele biber crepa 30x15.jpg",
      "/Listele biber crepa 30x15 2.jpg",
      "/Listele biber crepa 30x15 3.jpg",
      "/Listele biber crepa 30x15 4.jpg",
      "/Listele biber crepa 30x15 5.jpg",
      "/Listele biber crepa 30x15 6.jpg",
      "/Listele biber crepa 30x15 7.jpg",
    ],
  },
  {
    id: 2,
    title: "Listele od biber crepa 15x5 cm",
    text: "Sečene od autentičnog starog biber crepa, ove pločice dimenzija 15x5 cm idealne su za zidne obloge. Izrađene od prirodnih materijala, odlikuju se visokim stepenom otpornosti na spoljne uticaje. Savršen izbor za rustične i moderne prostore koji zahtevaju dugotrajnost i estetsku vrednost.",
    price: 16,
    ground: " - zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " - samo za staze bez vecih opterecenja",
    images: [
      "/Listele od biber crepa 15x5 cm 2.jpg",
      "/Listele od biber crepa 15x5 cm.jpg",
    ],
  },
  {
    id: 3,
    title: "Dekorativne ciglice od biber crepa 7.5x30 cm",
    text: "Sečene od autentičnog starog biber crepa, ove pločice dimenzija 8x30 cm idealne su za podne i zidne obloge. Izrađene od prirodnih materijala, odlikuju se visokim stepenom otpornosti na spoljne uticaje i mogu podneti velika opterecenja. Savršen izbor za rustične i moderne prostore koji zahtevaju dugotrajnost i estetsku vrednost.",
    price: 11,
    ground: " - podna i zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " - Podnosi velika opterecenja",
    images: [
      "/7.5x30 (2).jpg",
      "/7.5x30 (3).jpg",
      "/7.5x30 (4).jpg",
      "/7.5x30 (1).jpg",
      "/Dekorativne ciglice od biber crepa 8x30 cm 6.jpg",
      "/Dekorativne ciglice od biber crepa 8x30 cm 2.jpg",
      "/Dekorativne ciglice od biber crepa 8x30 cm.jpg",
      "/Dekorativne ciglice od biber crepa 8x30 cm 3.jpg",
      "/Dekorativne ciglice od biber crepa 8x30 cm 4.jpg",
      "/Dekorativne ciglice od biber crepa 8x30 cm 5.jpg",
      "/20250209_230254.jpg",
    ],
  },
  {
    id: 4,
    title: "Dekorativne ciglice 15x30 cm, crveno-žuta kombinacija",
    text: "Ove dekorativne ciglice dimenzija 15x30 cm, u kombinaciji crvenih i žutih tonova, idealne su za podne i zidne obloge. Sečene od prirodnih materijala, odlikuju se visokom otpornošću na spoljne uticaje i mogu podneti velika opterećenja. Pored izdržljivosti, pružaju i odličnu toplotnu izolaciju, čineći svaki prostor estetski privlačnim i energetski efikasnim.",
    price: 11,
    ground: " - podna i zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " - Podnosi velika opterecenja",
    images: [
      "/Listele i dekorativne ciglice 15 x 30 cm.jpg",
      "/Listele i dekorativne ciglice 15 x 30 cm 2.jpg",
      "/Listele i dekorativne ciglice 15 x 30 cm 3.jpg",
    ],
  },
  {
    id: 5,
    title: "Dekorativne ciglice 26x6 cm",
    text: "Ove dekorativne ciglice dimenzija 26x6 cm simulacija fasadne cigle, u kombinaciji crvenih i žutih tonova, idealne su za podne i zidne obloge. Sečene od prirodnih materijala, odlikuju se visokom otpornošću na spoljne uticaje i mogu podneti velika opterećenja. Pored izdržljivosti, pružaju i odličnu toplotnu izolaciju, čineći svaki prostor estetski privlačnim i energetski efikasnim.",
    price: 13,
    ground: " - podna i zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " - Podnosi velika opterecenja",
    images: [
      "/Dekorativne ciglice 26x6.jpg",
      "/Dekorativne ciglice 26x6 (1).jpg",
      "/Dekorativne ciglice 26x5,5 cm2.jpg",
      "/Dekorativne ciglice 26x5,5 cm1.jpg",
      "/Dekorativne ciglice 26x5,5 cm3.jpg",
      "/Dekorativne ciglice 26x5,5 cm.jpg",
      "/Dekorativne ciglice 26x5,5 cm4.jpg",
      "/Dekorativne ciglice 26x5,5 cm5.jpg",
    ],
  },
  {
    id: 7,
    title: "Listele od biber crepa zute",
    text: "Sečene od autentičnog starog biber crepa, ove pločice dimenzija cm idealne su za podne i zidne obloge. Izrađene od prirodnih materijala, odlikuju se visokim stepenom otpornosti na spoljne uticaje i mogu podneti teret veći od 12 tona. Savršen izbor za rustične i moderne prostore koji zahtevaju dugotrajnost i estetsku vrednost.",
    price: 12,
    ground: " - podna i zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " - Podnosi opterecenje 12 tona",
    images: [
      "/Listele od biber crepa 30x15 zute (8).jpg",
      "/Listele od biber crepa 30x15 zute (5).jpg",
      "/Listele od biber crepa 30x15 zute (6).jpg",
      "/Listele od biber crepa 30x15 zute (7).jpg",
      "/Listele od biber crepa 30x15 zute.jpg",
      "/Listele od biber crepa 30x15 zute2.jpg",
    ],
  },
  {
    id: 8,
    title: "Prirodni lomljeni kamen",
    text: "Izrađen od 100% prirodnog materijala, ovaj kamen je idealan za zidne i podne obloge. Odlikuje se visokom otpornošću na spoljne uticaje i velika opterećenja, pružajući dugotrajnost i autentičnu estetiku. Savršen izbor za eksterijere i enterijere koji zahtevaju prirodnu eleganciju i izdržljivost.",
    price: 7,
    ground: " - podna i zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " - Podnosi velika opterecenja",
    images: [
      "/Prirodni lomljeni kamen.jpg",
      "/Prirodni lomljeni kamen 2.jpg",
      "/Prirodni lomljeni kamen 3.jpg",
      "/Prirodni lomljeni kamen 4.jpg",
      "/Prirodni lomljeni kamen 5.jpg",
    ],
  },

  {
    id: 19,
    title: "Svabska opeka, 29-31cm",
    text: "Svabska opeka secena u listele, dimenzije variraju od 29cm do 31cm. Moze da se krate na iste dimenzije onda je cena 15e",
    price: 16,
    ground: " - zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: " - nije za velika opterecenja",
    images: ["/svabska cigla.jpg"],
  },
  {
    id: 20,
    title: "Crep 45 stepeni",
    text: "Crep 45 stepeni za zid i pod",
    price: 16,
    ground: " - podna i zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: "",
    images: ["/crep45.jpg"],
  },
  {
    id: 21,
    title: "Farbanje cigala",
    text: "Mogu se farbati kod nas ili na mestu ugradnje, zavisno od zelje musterije farbanje kod nas je 2e, farbanje na povrsini ugradnje 3e",
    price: 2,
    ground: " - podna i zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: "",
    images: ["/farbana.jpg", "/farbana2.jpg", "/farbana3.jpg"],
  },
  {
    id: 22,
    title: "Domaca sumadijska listela 01",
    text: "Domaca sumadijska cigla, listela se koristi za zidnu ugradnju.",
    price: 17,
    ground: " - zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: "",
    images: [
      "/sumadijska (5).jpg",
      "/sumadijska.jpg",
      "/sumadijska (1).jpg",
      "/sumadijska (2).jpg",
      "/sumadijska (3).jpg",
      "/sumadijska (4).jpg",
    ],
  },
  {
    id: 23,
    title: "Domaca sumadijska listela 02",
    text: "Domaca sumadijska cigla, listela se koristi za zidnu ugradnju, sece se od unutrasnjeg dela cigle. Preporucuje se zastita nakon ugradnje",
    price: 12,
    ground: " - zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: "",
    images: [
      "/sumadijska2 (5).jpg",
      "/sumadijska2 (1).jpg",
      "/sumadijska2 (2).jpg",
      "/sumadijska2 (3).jpg",
      "/sumadijska2 (4).jpg",
    ],
  },
  {
    id: 24,
    title: "Crep Kolubara",
    text: "Crep Kolubara se koristi za zidnu i podnu ugradnju.Trpi velike tezine, otporan na sve",
    price: 10,
    ground: " -podna i zidna obloga",
    eco: " - prirodni materijali",
    outside: " - za spoljasnju i unutrasnju ugradnju",
    weight: "Podnosi velike tezine",
    images: [
      "/Crep Kolubara (3).jpg",
      "/Crep Kolubara (4).jpg",
      "/Crep Kolubara (1).jpg",
      "/Crep Kolubara (2).jpg",
    ],
  },
];
